### ISSUE TITLE
CPLSetConfigOption GDAL_DATA has no effect on Windows

### ISSUE THREAD

**Issue by iwer** [TensorWorks/UnrealGDAL#2]
While using `GDALHelpers::WktFromEPSG` on a Windows system I discovered that it seems like `CPLSetConfigOption("GDAL_DATA", "C:/Path/to/Project/Binaries/Data/GDAL");` does not enable GDAL to find the necessary gcs.csv file. The file is where it should be and `CPLGetConfigOption` returns the expected value.

The [GDAL-Docs](https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_DATA) state:  "On Windows platform, this option must be generally declared."

So the only solution for Windows seems to be to set GDAL_DATA as environment variable to "C:/Path/to/Project/Binaries/Data/GDAL".

**Comment by adamrehn** [comment]
We've tested the plugin extensively under Windows and it's always found the data files correctly in our tests. Could you please answer the following questions to provide some context:

- What version of the Unreal Engine are you using?
- Have you correctly loaded the UnrealGDAL module and called `UnrealGDAL->InitGDAL()` as per the instructions in [the Usage section of the README](https://github.com/TensorWorks/UnrealGDAL/blob/v0.0.1/README.md#usage)?

**Comment by iwer** [comment]
This happens to me with UE 4.26 using VS2019. I only started using `GDALHelpers::WktFromEPSG()` in 4.26. In 4.25 I was using `OGRSpatialReference::SetWellKnownGeogCS()` and `OGRSpatialReference::SetUTM()` which didn't have any problems, although it might be, that those methods don't rely on the gdal_data files.

I am initializing UnrealGDAL in`StartupModule()` of a runtime plugin consuming the GDAL Api:
.uplugin
```json
"Modules": [
        {
            "Name": "GeoReference",
            "Type": "Runtime",
            "LoadingPhase": "Default"
        }
    ],
    "Plugins": [
         {
            "Name": "UnrealGDAL",
            "Enabled": true
         }
    ]
```
.Build.cs
```c#
PublicDependencyModuleNames.AddRange(
            new string[]
            {
                "Core",
                "GDAL",
                "UnrealGDAL",
                "Landscape",
                // ... add other public dependencies that you statically link with here ...
            }
            );
```
Module.cpp
```c++
FUnrealGDALModule* UnrealGDAL = FModuleManager::Get().LoadModulePtr<FUnrealGDALModule>("UnrealGDAL");
UnrealGDAL->InitGDAL();

UE_LOG(LogTemp, Warning, TEXT("FGeoReferenceModule: Initialized GDAL"));

auto gdaldata = CPLGetConfigOption("GDAL_DATA", NULL);
if (gdaldata != NULL) {
    FString dir(ANSI_TO_TCHAR(gdaldata));
    UE_LOG(LogTemp, Warning, TEXT("FGeoReferenceModule: Data directory: %s"), *dir);
}
```
Although initially there are some errors, the output seems to confirm that the config variable is set at the end:
```log
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
[2021.01.29-08.38.46:513][  0]LogTemp: Error: UGeoCoordinate: Error constructing OGRSpatialReference from EPSG number 4326
ERROR 1: No PROJ.4 translation for source SRS, coordinate transformation initialization has failed.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
[2021.01.29-08.38.46:523][  0]LogTemp: Error: UGeoCoordinate: Error constructing OGRSpatialReference from EPSG number 4326
ERROR 1: No PROJ.4 translation for source SRS, coordinate transformation initialization has failed.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
[2021.01.29-08.38.46:535][  0]LogTemp: Error: UGeoCoordinate: Error constructing OGRSpatialReference from EPSG number 32731
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
[2021.01.29-08.38.46:543][  0]LogTemp: Error: UGeoCoordinate: Error constructing OGRSpatialReference from EPSG number 4326
ERROR 1: No PROJ.4 translation for source SRS, coordinate transformation initialization has failed.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
[2021.01.29-08.38.46:553][  0]LogTemp: Error: UGeoCoordinate: Error constructing OGRSpatialReference from EPSG number 4326
ERROR 1: No PROJ.4 translation for source SRS, coordinate transformation initialization has failed.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
[2021.01.29-08.38.46:566][  0]LogTemp: Error: UGeoCoordinate: Error constructing OGRSpatialReference from EPSG number 32731
[2021.01.29-08.38.46:570][  0]LogTemp: Warning: FGeoReferenceModule: Initialized GDAL
[2021.01.29-08.38.46:570][  0]LogTemp: Warning: FGeoReferenceModule: Data directory: D:/UnrealProjects/GeotiffLandscape_Dev/Binaries/Data/GDAL
[2021.01.29-08.38.46:615][  0]LogEngine: Initializing Engine...
```
The files are indeed in this directory, as expected.

Then, when using 
```c++
FString wkt = GDALHelpers::WktFromEPSG(EPSGNumber,true);
auto err = targetSRS.importFromWkt(TCHAR_TO_ANSI(*wkt));
if(err != OGRERR_NONE) {
    UE_LOG(LogTemp, Error, TEXT("UGeoCoordinate: Error constructing OGRSpatialReference from EPSG number %d"), EPSGNumber);
    return UGeoCoordinate::DVector2D();
}
```
however, I get:
```
[2021.01.29-08.39.19:474][728]LogTemp: Error: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
[2021.01.29-08.39.19:481][728]LogTemp: Error: UGeoCoordinate: Error constructing OGRSpatialReference from EPSG number 4326
[2021.01.29-08.39.19:481][728]LogTemp: Error: No PROJ.4 translation for source SRS, coordinate transformation initialization has failed.
```

I didn't think much about the initial errors, before UnrealGDAL is initialized, as I attributed them to the reflection magic of UE, but thinking of it, this might actually be my fault. Obviously UE creates instances of classes of my Plugin that use UnrealGDAL before UnrealGDAL is initialized. If i understand it correctly those instances are then used at runtime to create new instances. 

Is it sufficient to initialize UnrealGDAL only in a Plugin and then using only that Plugins API in a GameModule, or is it necessary to also initalize UnrealGDAL in every module that uses that Plugin?

**Comment by iwer** [comment]
My problem was to call this method somewhere down a default constructor which gets called during initialization of the engine to create a prototype for following objects. This seems to happen before StartupModule() gets called. The initialization of UnrealGDAL succeeds but later created objects of this class see GDAL_DATA as unset.

t.l.d.r: Getting rid of the calls to `GDALHelpers::WktFromEPSG();` in default constructors solves the problem.

**Comment by adamrehn** [comment]
That's a bit of a nasty edge case, I'm glad you were able to track it down! To answer your question, you need to initialise UnrealGDAL in every C++ code module that uses it, regardless of where they are located in the project or other plugins, since each module gets compiled into its own separate shared library and process-wide GDAL configuration changes do not propagate across DLL boundaries under Windows.
