### ISSUE TITLE
The /precomputed directory should not be gitignored for releases

### ISSUE THREAD

**Issue by connorjak** [TensorWorks/UnrealGDAL#3]
If the release downloader is using this plugin inside of a git repository, and depending on the precomputed files for their setup, the precomputed files being gitignored (in `UnrealGDAL/Source/GDAL/.gitignore`) means those files will be discarded for the purposes of that git repo.

**Comment by MadaraPremawardhana** [comment]
Hi @adamrehn I am still getting this when trying to build precomputes for UE version 4.26 for the GDAL library when trying to use LandscapeGen plugin. 

`Set engine root path override: C:\Program Files\Epic Games\UE_4.26\Engine\Build
Using user-specified engine root: C:\Program Files\Epic Games\UE_4.26\Engine\Build
Warning: the specified directory does not appear to contain a valid version of the Unreal Engine.`

Also will you be able to release the precomputes for UE 4.26  in https://github.com/TensorWorks/UnrealGDAL/releases

**Comment by adamrehn** [comment]
@connorjak I've now updated the zip file for the existing release to remove the offending line in the mentioned `.gitignore` file, as well as completely remove the `.gitignore` file from the `ThirdParty` directory. This will also be reflected in any potential future releases, although I'm unsure as to whether this plugin will continue to be relevant with the [heavy investment in this space from players such as Cesium](https://cesium.com/platform/cesium-for-unreal/).

@MadaraPremawardhana you have set the root path incorrectly. You need to remove `Engine\Build` from the end of the path and it should then work correctly.
